### ISSUE TITLE
Error on push eCars code to an Scratch org

### ISSUE THREAD

**Issue by magaiverf** [trailheadapps/ecars#152] opened 2021-02-17 18:05 UTC
Hi folks,
I've clone the eCars repository to follow the Modern App Development youtube series and I faced the issue below when I tried to push the code to the scratch org:

_Cannot specify a startsWith attribute for this language_

It's happening in the **Car_Options__c.object-meta.xml**

Thanks!

**Comment by magaiverf** [comment] 2021-02-17 18:09
> Hi folks,
> I've clone the eCars repository to follow the Modern App Development youtube series and I faced the issue below when I tried to push the code to the scratch org:
> 
> _Cannot specify a startsWith attribute for this language_
> 
> It's happening in the **Car_Options__c.object-meta.xml**
> 
> Thanks!

Hey All,
I "fixed"the issue removing the attribute _startWith_ from Car_Options__c, but I really don't know if it is the best approach.
Thanks

**Comment by msrivastav13** [comment] 2021-02-17 18:11
@magaiverf Can you provide some more info so we can replicate this?

- Are you using scratch org? If yes can you let me know the exact steps you followed?
- Can you let me know your CLI version?
- Also did you add a language parameter somewhere?

Thank you

**Comment by magaiverf** [comment] 2021-02-17 18:20
> @magaiverf Can you provide some more info so we can replicate this?
> 
> * Are you using scratch org? If yes can you let me know the exact steps you followed?
> * Can you let me know your CLI version?
> * Also did you add a language parameter somewhere?
> 
> Thank you

Hi @msrivastav13, sure...

- Are you using scratch org? Yes. 
  - Steps: 1 - clone the repository. 2 - Enable the Dev Hub on salesforce org and in the VSCode. 3 - Create a default scratch org. 4 - Tried to push the code.
-  Can you let me know your CLI version? sfdx-cli/7.85.1-2fb9e41053
- Also did you add a language parameter somewhere? No, I didn't.

P.S. I'm using a playground org.
Thanks!

**Comment by msrivastav13** [comment] 2021-02-17 18:22
@magaiverf Thank you for the response! What's the default Devhub language and also the default language of your scratch org?

**Comment by msrivastav13** [comment] 2021-02-17 18:35
Yep, company profile in Set up, and you will find it?

**Comment by magaiverf** [comment] 2021-02-17 18:40
It's English as well.

**Comment by msrivastav13** [comment] 2021-02-17 18:41
Interesting as I am not able to repro this at all! However, that metadata for `startsWith` is not needed at all. I am removing it!

**Comment by msrivastav13** [comment] 2021-02-17 23:30
@magaiverf closing it now! We have a temporary fix in place but have notified the product team of this metadata glitch!

**Closed by msrivastav13** 2021-02-17 23:30 UTC

**Comment by msrivastav13** [comment] 2021-02-18 03:44
@magaiverf I am working with the product on the root cause of this issue! How should I contact you?

I have few more questions

1. What Instance your DevHub is on?
2. What instance your scratch org is on?

Instructions are [here](https://help.salesforce.com/articleView?id=000322728&type=1&mode=1) to help you find your instance!

Thank you again for reporting the bug!
